// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmCSVbs_SQs18esQ23dQlKYFmgxTcxKdA',
    appId: '1:538757616550:web:a3b0f65fadcb1f21aef567',
    messagingSenderId: '538757616550',
    projectId: 'hasan-abbas-portfolio',
    authDomain: 'hasan-abbas-portfolio.firebaseapp.com',
    storageBucket: 'hasan-abbas-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK5j7JAXxxIdtsbzYbMZSPSjr6vUL48hs',
    appId: '1:538757616550:android:cb9c0c0928cc4b9baef567',
    messagingSenderId: '538757616550',
    projectId: 'hasan-abbas-portfolio',
    storageBucket: 'hasan-abbas-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaS0PMvi1QXnWU1oS-W3hE2DRVXJKcbJk',
    appId: '1:538757616550:ios:2135afcf1157d335aef567',
    messagingSenderId: '538757616550',
    projectId: 'hasan-abbas-portfolio',
    storageBucket: 'hasan-abbas-portfolio.firebasestorage.app',
    androidClientId: '538757616550-ut2v23v9592rngjfcajtteifo8lpot1k.apps.googleusercontent.com',
    iosClientId: '538757616550-70sh6itep3ravdeta37qg9ovip318v0l.apps.googleusercontent.com',
    iosBundleId: 'hasanabbas.dev.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaS0PMvi1QXnWU1oS-W3hE2DRVXJKcbJk',
    appId: '1:538757616550:ios:2135afcf1157d335aef567',
    messagingSenderId: '538757616550',
    projectId: 'hasan-abbas-portfolio',
    storageBucket: 'hasan-abbas-portfolio.firebasestorage.app',
    androidClientId: '538757616550-ut2v23v9592rngjfcajtteifo8lpot1k.apps.googleusercontent.com',
    iosClientId: '538757616550-70sh6itep3ravdeta37qg9ovip318v0l.apps.googleusercontent.com',
    iosBundleId: 'hasanabbas.dev.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmCSVbs_SQs18esQ23dQlKYFmgxTcxKdA',
    appId: '1:538757616550:web:d320e6f52a1e84d0aef567',
    messagingSenderId: '538757616550',
    projectId: 'hasan-abbas-portfolio',
    authDomain: 'hasan-abbas-portfolio.firebaseapp.com',
    storageBucket: 'hasan-abbas-portfolio.firebasestorage.app',
  );
}
