name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "TURSO_URL=${{ secrets.TURSO_URL }}" > .env
          echo "TURSO_TOKEN=${{ secrets.TURSO_TOKEN }}" >> .env
          echo "APP_NAME=Portfolio" >> .env
          echo "DEFAULT_LOCALE=en" >> .env

      - name: Build Web App
        run: flutter build web --release --base-href "/Portfolio_by_hasan/" --dart-define=TURSO_URL="${{ secrets.TURSO_URL }}" --dart-define=TURSO_TOKEN="${{ secrets.TURSO_TOKEN }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
